# Generated by Django 6.0.6 on 2026-07-22 15:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("retired", "Retired"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("alias", models.CharField(blank=True, default="", max_length=80)),
                ("pronouns", models.CharField(blank=True, default="", max_length=80)),
                ("metatype", models.CharField(blank=True, default="", max_length=80)),
                (
                    "archetype_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "short_concept",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("backstory", models.TextField()),
                ("body", models.PositiveSmallIntegerField()),
                ("agility", models.PositiveSmallIntegerField()),
                ("reaction", models.PositiveSmallIntegerField()),
                ("strength", models.PositiveSmallIntegerField()),
                ("willpower", models.PositiveSmallIntegerField()),
                ("logic", models.PositiveSmallIntegerField()),
                ("intuition", models.PositiveSmallIntegerField()),
                ("charisma", models.PositiveSmallIntegerField()),
                ("edge", models.PositiveSmallIntegerField()),
                ("essence", models.DecimalField(decimal_places=2, max_digits=4)),
                ("magic", models.PositiveSmallIntegerField()),
                ("resonance", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redmond_sheet",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.CharField(max_length=80)),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ("skill_id", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("approved", "retired", "archived"))),
                name="sheet_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.GreaterThan(
                    django.db.models.functions.text.Length(
                        django.db.models.functions.text.Replace(
                            django.db.models.functions.text.Replace(
                                django.db.models.functions.text.Replace(
                                    django.db.models.functions.text.Replace(
                                        models.F("backstory"),
                                        models.Value("\r"),
                                        models.Value(""),
                                    ),
                                    models.Value("\n"),
                                    models.Value(""),
                                ),
                                models.Value("\t"),
                                models.Value(""),
                            ),
                            models.Value(" "),
                            models.Value(""),
                        )
                    ),
                    models.Value(0),
                ),
                name="sheet_backstory_visible_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("body__gte", 0), ("body__lte", 99)),
                name="sheet_body_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("agility__gte", 0), ("agility__lte", 99)),
                name="sheet_agility_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("reaction__gte", 0), ("reaction__lte", 99)),
                name="sheet_reaction_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("strength__gte", 0), ("strength__lte", 99)),
                name="sheet_strength_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("willpower__gte", 0), ("willpower__lte", 99)),
                name="sheet_willpower_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("logic__gte", 0), ("logic__lte", 99)),
                name="sheet_logic_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("intuition__gte", 0), ("intuition__lte", 99)),
                name="sheet_intuition_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("charisma__gte", 0), ("charisma__lte", 99)),
                name="sheet_charisma_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("edge__gte", 0), ("edge__lte", 99)),
                name="sheet_edge_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("magic__gte", 0), ("magic__lte", 99)),
                name="sheet_magic_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("resonance__gte", 0), ("resonance__lte", 99)),
                name="sheet_resonance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactersheet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("essence__gte", 0), ("essence__lte", Decimal("99.99"))
                ),
                name="sheet_essence_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="characterskill",
            index=models.Index(
                fields=["sheet", "skill_id"], name="sheet_skill_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterskill",
            constraint=models.UniqueConstraint(
                fields=("sheet", "skill_id"), name="sheet_skill_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 99)),
                name="sheet_skill_rating_positive",
            ),
        ),
    ]
