# Generated by Django 6.0.6 on 2026-07-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "objects",
            "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargenRulesProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_key", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField()),
                ("display_name", models.CharField(max_length=120)),
                (
                    "is_available_for_new_sessions",
                    models.BooleanField(default=True),
                ),
                (
                    "is_default_for_new_sessions",
                    models.BooleanField(default=False),
                ),
                ("starting_karma", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("profile_key", "version", "id"),
            },
        ),
        migrations.CreateModel(
            name="ChargenSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("abandoned", "Abandoned"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("starting_karma_snapshot", models.PositiveIntegerField()),
                ("backstory", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redmond_chargen_sessions",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "rules_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="chargen.chargenrulesprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="chargenrulesprofile",
            constraint=models.UniqueConstraint(
                fields=("profile_key", "version"),
                name="chargen_profile_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargenrulesprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_default_for_new_sessions", True)
                ),
                fields=("is_default_for_new_sessions",),
                name="chargen_default_profile_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargenrulesprofile",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("is_default_for_new_sessions", False))
                    | models.Q(("is_available_for_new_sessions", True))
                ),
                name="chargen_default_requires_available",
            ),
        ),
        migrations.AddIndex(
            model_name="chargenrulesprofile",
            index=models.Index(
                fields=["profile_key", "is_available_for_new_sessions"],
                name="chargen_profile_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "draft",
                            "submitted",
                            "changes_requested",
                            "approved",
                            "abandoned",
                            "superseded",
                        ),
                    )
                ),
                name="chargen_session_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_karma_snapshot__gte", 0)),
                name="chargen_session_karma_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("draft", "submitted", "changes_requested"),
                    )
                ),
                fields=("character",),
                name="chargen_active_session_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="chargensession",
            index=models.Index(
                fields=["character", "status"],
                name="chargen_character_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chargensession",
            index=models.Index(
                fields=["character", "created_at"],
                name="chargen_character_created_idx",
            ),
        ),
    ]
