# Generated by Codex on 2026-08-01.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargensession",
            name="agility",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="body",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="charisma",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="edge",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="intuition",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="logic",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="reaction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="strength",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chargensession",
            name="willpower",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("body__isnull", True))
                    | models.Q(("body__gte", 0), ("body__lte", 99))
                ),
                name="chargen_body_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("agility__isnull", True))
                    | models.Q(("agility__gte", 0), ("agility__lte", 99))
                ),
                name="chargen_agility_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("reaction__isnull", True))
                    | models.Q(("reaction__gte", 0), ("reaction__lte", 99))
                ),
                name="chargen_reaction_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("strength__isnull", True))
                    | models.Q(("strength__gte", 0), ("strength__lte", 99))
                ),
                name="chargen_strength_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("willpower__isnull", True))
                    | models.Q(
                        ("willpower__gte", 0),
                        ("willpower__lte", 99),
                    )
                ),
                name="chargen_willpower_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("logic__isnull", True))
                    | models.Q(("logic__gte", 0), ("logic__lte", 99))
                ),
                name="chargen_logic_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("intuition__isnull", True))
                    | models.Q(
                        ("intuition__gte", 0),
                        ("intuition__lte", 99),
                    )
                ),
                name="chargen_intuition_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("charisma__isnull", True))
                    | models.Q(
                        ("charisma__gte", 0),
                        ("charisma__lte", 99),
                    )
                ),
                name="chargen_charisma_draft_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargensession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("edge__isnull", True))
                    | models.Q(("edge__gte", 0), ("edge__lte", 99))
                ),
                name="chargen_edge_draft_valid",
            ),
        ),
    ]
